# Generated by Django 3.1 on 2021-06-29 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainapp', '0003_product_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='СЃРѕР·РґР°РЅ')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='РѕР±РЅРѕРІР»РµРЅ')),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('FM', 'С„РѕСЂРјРёСЂСѓРµС‚СЃСЏ'), ('STP', 'РѕС‚РїСЂР°РІР»РµРЅ РІ РѕР±СЂР°Р±РѕС‚РєСѓ'), ('PRD', 'РѕР±СЂР°Р±РѕС‚Р°РЅ'), ('PD', 'РѕРїР»Р°С‡РµРЅ'), ('RD', 'Р“РѕС‚РѕРІ Рє РІС‹РґР°С‡Рµ'), ('CNC', 'РћС‚РјРµРЅРµРЅ'), ('DVD', 'Р’С‹РґР°РЅ')], default='FM', max_length=3, verbose_name='СЃС‚Р°С‚СѓСЃ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='РєРѕР»РёС‡РµСЃС‚РІРѕ')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderitems', to='ordersapp.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.product', verbose_name='РїСЂРѕРґСѓРєС‚')),
            ],
        ),
    ]
